name: Build, Publish, and Deploy

on:
  push:
    branches:
      - main  

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml  

  build-publish-deploy:
    runs-on: ubuntu-latest
    needs: run-tests  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Criar arquivo .env
        run: |
          touch .env
          echo "VITE_HOST_API=${{ vars.VITE_HOST_API }}" > .env
 

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: despossivel/managerticketsfront:${{ steps.slug.outputs.sha8 }}

      # - name: Replace image tag in deployment.yml
      #   run: sed -i 's|managerticketsfront:TAG|managerticketsfront:${{ steps.slug.outputs.sha8 }}|g' ./.k8s/deployment.yml

      # - name: Set up kubectl
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: Set up Kubernetes context
      #   uses: Azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f ./.k8s/deployment.yml
      #     kubectl apply -f ./.k8s/service.yml
